"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import type { ClothingAttributes, EditableAttributes } from "@/lib/schemas/ai";
import {
  cleanGarmentPhoto,
  NothingDetectedError,
  UnsupportedImageError,
  type CleanProgress,
} from "@/lib/image/clean";

// The add-item flow lives here rather than in the page component so it
// survives navigation. The (app) layout stays mounted while the user moves
// between tabs, so a picked photo, a running background removal, an in-flight
// analysis and an unsaved review all persist until saved, discarded, or the
// page is hard-refreshed.

export type Step = "pick" | "analyzing" | "review" | "saving";

export type BgStatus = "idle" | "running" | "done" | "failed" | "unsupported" | "skipped";
export type CropStatus = "idle" | "running" | "done" | "failed";
export type EnhanceMode = "isolate" | "iron";
export type EnhanceStatus = "idle" | "running" | "done" | "failed";
export type ImageChoice = "original" | "cropped" | "cleaned" | "isolated" | "ironed";

export const CHECKLIST = [
  "Image accepted",
  "Garment identified",
  "Colour and pattern sampled",
  "Rated for Singapore weather",
];

export const emptyAttrs: ClothingAttributes = {
  category: "top",
  subcategory: "",
  primary_colour: "",
  secondary_colours: [],
  pattern: "",
  material_cues: "",
  formality: "casual",
  layering_role: "base",
  weather_tags: [],
  confidence_notes: "",
  uncertain_fields: [],
};

type State = {
  step: Step;
  // The photo exactly as picked, and its object URL
  original: File | null;
  originalPreview: string | null;
  // Output of background removal, once available
  cleaned: File | null;
  cleanedPreview: string | null;
  // Fallback crop to the garment when removal fails, once available
  cropped: File | null;
  croppedPreview: string | null;
  // Generated by the image model on request, or as a fallback
  isolated: File | null;
  isolatedPreview: string | null;
  ironed: File | null;
  ironedPreview: string | null;
  enhance: Record<EnhanceMode, { status: EnhanceStatus; message: string | null }>;
  // Which version the user wants to analyse and save
  choice: ImageChoice;
  crop: { status: CropStatus };
  bg: {
    status: BgStatus;
    phase: "download" | "process";
    // 0..1 while downloading the model
    progress: number;
    message: string | null;
  };
  attrs: ClothingAttributes;
  // Fields the AI filled in. Empty until an analysis has returned
  aiTouched: boolean;
  // Fields the user has since edited, so their AI tag disappears
  edited: Set<string>;
  notes: string;
  error: string | null;
  // Checklist progress shown while analyzing
  done: number;
};

type Api = State & {
  // The file and preview that analysis and saving will use
  file: File | null;
  preview: string | null;
  pickFile: (file: File | null) => void;
  chooseImage: (which: ImageChoice) => void;
  skipClean: () => void;
  retryClean: () => void;
  requestEdit: (mode: EnhanceMode) => void;
  analyze: () => Promise<void>;
  setField: <K extends keyof EditableAttributes>(key: K, value: EditableAttributes[K]) => void;
  setNotes: (notes: string) => void;
  setStep: (step: Step) => void;
  setError: (error: string | null) => void;
  reset: () => void;
};

const idleBg: State["bg"] = { status: "idle", phase: "download", progress: 0, message: null };

const initial: State = {
  step: "pick",
  original: null,
  originalPreview: null,
  cleaned: null,
  cleanedPreview: null,
  cropped: null,
  croppedPreview: null,
  isolated: null,
  isolatedPreview: null,
  ironed: null,
  ironedPreview: null,
  enhance: { isolate: { status: "idle", message: null }, iron: { status: "idle", message: null } },
  choice: "cleaned",
  crop: { status: "idle" },
  bg: idleBg,
  attrs: emptyAttrs,
  aiTouched: false,
  edited: new Set(),
  notes: "",
  error: null,
  done: 0,
};

const AnalysisContext = createContext<Api | null>(null);

export function useAnalysis() {
  const ctx = useContext(AnalysisContext);
  if (!ctx) throw new Error("useAnalysis must be used inside AnalysisProvider");
  return ctx;
}

function revoke(state: State) {
  if (state.originalPreview) URL.revokeObjectURL(state.originalPreview);
  if (state.cleanedPreview) URL.revokeObjectURL(state.cleanedPreview);
  if (state.croppedPreview) URL.revokeObjectURL(state.croppedPreview);
  if (state.isolatedPreview) URL.revokeObjectURL(state.isolatedPreview);
  if (state.ironedPreview) URL.revokeObjectURL(state.ironedPreview);
}

export function AnalysisProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<State>(initial);
  const controller = useRef<AbortController | null>(null);
  const cleanController = useRef<AbortController | null>(null);
  const enhanceController = useRef<AbortController | null>(null);
  const timers = useRef<ReturnType<typeof setTimeout>[]>([]);
  const stateRef = useRef(state);
  // The removal library cannot be aborted, so results are tagged with the
  // generation they belong to and stale ones are ignored
  const generation = useRef(0);

  const clearTimers = () => {
    timers.current.forEach(clearTimeout);
    timers.current = [];
  };

  useEffect(() => {
    stateRef.current = state;
  }, [state]);

  useEffect(
    () => () => {
      controller.current?.abort();
      cleanController.current?.abort();
      enhanceController.current?.abort();
      generation.current++;
      timers.current.forEach(clearTimeout);
      revoke(stateRef.current);
    },
    [],
  );

  // Image model edit. "isolate" cuts the garment onto white, "iron" also
  // flattens it like a catalogue photo. Always works from the original photo
  // so repeated edits do not compound. This is paid and only runs after an
  // explicit user action.
  const runEnhance = useCallback(async (file: File, mode: EnhanceMode, gen: number) => {
    enhanceController.current?.abort();
    const ac = new AbortController();
    enhanceController.current = ac;
    setState((prev) => ({
      ...prev,
      enhance: { ...prev.enhance, [mode]: { status: "running", message: null } },
    }));
    try {
      const form = new FormData();
      form.set("image", file);
      form.set("mode", mode);
      const res = await fetch("/api/items/enhance", {
        method: "POST",
        body: form,
        signal: ac.signal,
      });
      if (gen !== generation.current) return false;
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? "Image edit failed");
      }
      const blob = await res.blob();
      if (gen !== generation.current) return false;
      const ext = blob.type === "image/png" ? "png" : "jpg";
      const base = file.name.replace(/\.[^.]+$/, "") || "item";
      const edited = new File([blob], `${base}-${mode}.${ext}`, { type: blob.type });
      const key = mode === "isolate" ? "isolated" : "ironed";
      const previewKey = mode === "isolate" ? "isolatedPreview" : "ironedPreview";
      setState((prev) => {
        if (prev[previewKey]) URL.revokeObjectURL(prev[previewKey] as string);
        return {
          ...prev,
          [key]: edited,
          [previewKey]: URL.createObjectURL(edited),
          choice: key,
          enhance: { ...prev.enhance, [mode]: { status: "done", message: null } },
        };
      });
      return true;
    } catch (err) {
      if (ac.signal.aborted) return false;
      if (gen !== generation.current) return false;
      setState((prev) => ({
        ...prev,
        enhance: {
          ...prev.enhance,
          [mode]: {
            status: "failed",
            message: err instanceof Error ? err.message : "Image edit failed",
          },
        },
      }));
      return false;
    } finally {
      if (enhanceController.current === ac) enhanceController.current = null;
    }
  }, []);

  const runClean = useCallback((file: File) => {
    cleanController.current?.abort();
    const ac = new AbortController();
    cleanController.current = ac;
    const gen = ++generation.current;
    setState((prev) => ({
      ...prev,
      crop: { status: "idle" },
      bg: { status: "running", phase: "download", progress: 0, message: null },
    }));

    cleanGarmentPhoto(file, (p: CleanProgress) => {
      if (gen !== generation.current) return;
      setState((prev) => ({
        ...prev,
        bg:
          p.phase === "download"
            ? { ...prev.bg, phase: "download", progress: p.total ? p.loaded / p.total : 0 }
            : { ...prev.bg, phase: "process", progress: 1 },
      }));
    }, ac.signal)
      .then((cleaned) => {
        if (gen !== generation.current) return;
        setState((prev) => {
          if (prev.cleanedPreview) URL.revokeObjectURL(prev.cleanedPreview);
          return {
            ...prev,
            cleaned,
            cleanedPreview: URL.createObjectURL(cleaned),
            choice: "cleaned",
            bg: { status: "done", phase: "process", progress: 1, message: null },
          };
        });
      })
      .catch((err: unknown) => {
        if (ac.signal.aborted) return;
        if (gen !== generation.current) return;
        const unsupported = err instanceof UnsupportedImageError;
        const message = unsupported
          ? "This browser cannot decode HEIC photos, so the original will be used."
          : err instanceof NothingDetectedError
            ? "Couldn't separate the garment from the background. Using the original. Try a plain surface that contrasts with the item."
            : "Background removal did not work for this photo. Using the original.";
        setState((prev) => ({
          ...prev,
          choice: "original",
          bg: { status: unsupported ? "unsupported" : "failed", phase: "process", progress: 0, message },
        }));
      })
      .finally(() => {
        if (cleanController.current === ac) cleanController.current = null;
      });
  }, []);

  const reset = useCallback(() => {
    controller.current?.abort();
    controller.current = null;
    cleanController.current?.abort();
    cleanController.current = null;
    enhanceController.current?.abort();
    enhanceController.current = null;
    generation.current++;
    clearTimers();
    setState((prev) => {
      revoke(prev);
      return initial;
    });
  }, []);

  const pickFile = useCallback(
    (file: File | null) => {
      controller.current?.abort();
      controller.current = null;
      cleanController.current?.abort();
      cleanController.current = null;
      generation.current++;
      clearTimers();
      setState((prev) => {
        revoke(prev);
        return {
          ...initial,
          original: file,
          originalPreview: file ? URL.createObjectURL(file) : null,
        };
      });
      if (file) runClean(file);
    },
    [runClean],
  );

  const chooseImage = useCallback((which: ImageChoice) => {
    setState((prev) => {
      const available =
        which === "original" ||
        (which === "cleaned" && prev.cleaned) ||
        (which === "cropped" && prev.cropped) ||
        (which === "isolated" && prev.isolated) ||
        (which === "ironed" && prev.ironed);
      return available ? { ...prev, choice: which } : prev;
    });
  }, []);

  // User-initiated edit from the original photo
  const requestEdit = useCallback(
    (mode: EnhanceMode) => {
      if (state.original && state.enhance[mode].status !== "running") {
        void runEnhance(state.original, mode, generation.current);
      }
    },
    [state.original, state.enhance, runEnhance],
  );

  const skipClean = useCallback(() => {
    cleanController.current?.abort();
    cleanController.current = null;
    generation.current++;
    setState((prev) => ({
      ...prev,
      choice: "original",
      crop: { status: "idle" },
      bg: { status: "skipped", phase: "process", progress: 0, message: null },
    }));
  }, []);

  const retryClean = useCallback(() => {
    if (state.original) runClean(state.original);
  }, [state.original, runClean]);

  const versions: Record<ImageChoice, { file: File | null; preview: string | null }> = {
    original: { file: state.original, preview: state.originalPreview },
    cleaned: { file: state.cleaned, preview: state.cleanedPreview },
    cropped: { file: state.cropped, preview: state.croppedPreview },
    isolated: { file: state.isolated, preview: state.isolatedPreview },
    ironed: { file: state.ironed, preview: state.ironedPreview },
  };
  const chosen = versions[state.choice].file ? versions[state.choice] : versions.original;
  const file = chosen.file;
  const preview = chosen.preview;

  const analyze = useCallback(async () => {
    if (!file) return;

    controller.current?.abort();
    const ac = new AbortController();
    controller.current = ac;

    clearTimers();
    setState((prev) => ({ ...prev, step: "analyzing", error: null, done: 0 }));
    timers.current = CHECKLIST.map((_, i) =>
      setTimeout(() => setState((prev) => ({ ...prev, done: i + 1 })), 500 + i * 900),
    );

    const form = new FormData();
    form.set("image", file);

    try {
      const res = await fetch("/api/items/analyze", {
        method: "POST",
        body: form,
        signal: ac.signal,
      });
      const body = await res.json();
      if (ac.signal.aborted) return;
      clearTimers();

      if (!res.ok) {
        setState((prev) => ({ ...prev, step: "pick", error: body.error ?? "Analysis failed" }));
        return;
      }

      setState((prev) => ({
        ...prev,
        step: "review",
        attrs: { ...emptyAttrs, ...body.attributes },
        aiTouched: true,
        edited: new Set(),
        done: CHECKLIST.length,
      }));
    } catch (err) {
      if (ac.signal.aborted) return;
      clearTimers();
      setState((prev) => ({
        ...prev,
        step: "pick",
        error: err instanceof Error ? err.message : "Analysis failed",
      }));
    }
  }, [file]);

  const setField = useCallback(
    <K extends keyof EditableAttributes>(key: K, value: EditableAttributes[K]) => {
      setState((prev) => ({
        ...prev,
        attrs: { ...prev.attrs, [key]: value },
        edited: new Set(prev.edited).add(key),
      }));
    },
    [],
  );

  const setNotes = useCallback((notes: string) => setState((prev) => ({ ...prev, notes })), []);
  const setStep = useCallback((step: Step) => setState((prev) => ({ ...prev, step })), []);
  const setError = useCallback((error: string | null) => setState((prev) => ({ ...prev, error })), []);

  const api = useMemo<Api>(
    () => ({
      ...state,
      file,
      preview,
      pickFile,
      chooseImage,
      skipClean,
      retryClean,
      requestEdit,
      analyze,
      setField,
      setNotes,
      setStep,
      setError,
      reset,
    }),
    [state, file, preview, pickFile, chooseImage, skipClean, retryClean, requestEdit, analyze, setField, setNotes, setStep, setError, reset],
  );

  return <AnalysisContext.Provider value={api}>{children}</AnalysisContext.Provider>;
}
