"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "motion/react";
import {
  CLOTHING_CATEGORIES,
  FORMALITY_LEVELS,
  LAYERING_ROLES,
  WEATHER_TAGS,
  type ClothingAttributes,
} from "@/lib/schemas/ai";

type Step = "pick" | "analyzing" | "review" | "saving";

const emptyAttrs: ClothingAttributes = {
  category: "top",
  subcategory: "",
  primary_colour: "",
  secondary_colours: [],
  pattern: "",
  material_cues: "",
  formality: "casual",
  layering_role: "base",
  weather_tags: [],
  confidence_notes: "",
};

// Upload -> AI analysis -> user confirms or corrects -> save.
// The AI output is a suggestion; the confirmed form is what gets stored.
export function ItemUploader() {
  const router = useRouter();
  const [step, setStep] = useState<Step>("pick");
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [attrs, setAttrs] = useState<ClothingAttributes>(emptyAttrs);
  const [notes, setNotes] = useState("");
  const [error, setError] = useState<string | null>(null);

  function pickFile(next: File | null) {
    setFile(next);
    setError(null);
    setAttrs(emptyAttrs);
    setStep("pick");
    setPreview(next ? URL.createObjectURL(next) : null);
  }

  async function analyze() {
    if (!file) return;
    setStep("analyzing");
    setError(null);

    const form = new FormData();
    form.set("image", file);

    const res = await fetch("/api/items/analyze", { method: "POST", body: form });
    const body = await res.json();

    if (!res.ok) {
      setError(body.error ?? "Analysis failed");
      setStep("pick");
      return;
    }

    setAttrs({ ...emptyAttrs, ...body.attributes });
    setStep("review");
  }

  async function save() {
    if (!file) return;
    setStep("saving");
    setError(null);

    const form = new FormData();
    form.set("image", file);
    form.set("payload", JSON.stringify({ attributes: attrs }));
    form.set("user_notes", notes);

    const res = await fetch("/api/items", { method: "POST", body: form });
    const body = await res.json();

    if (!res.ok) {
      setError(body.error ?? "Could not save item");
      setStep("review");
      return;
    }

    router.push("/wardrobe");
    router.refresh();
  }

  function setField<K extends keyof ClothingAttributes>(
    key: K,
    value: ClothingAttributes[K],
  ) {
    setAttrs((prev) => ({ ...prev, [key]: value }));
  }

  return (
    <div className="space-y-6">
      <div>
        <label className="block text-sm font-medium">Clothing photo</label>
        <input
          type="file"
          accept="image/jpeg,image/png,image/webp,image/heic"
          onChange={(e) => pickFile(e.target.files?.[0] ?? null)}
          className="mt-2 block w-full text-sm text-stone-600 file:mr-4 file:rounded-lg file:border-0 file:bg-stone-900 file:px-4 file:py-2 file:text-sm file:text-white"
        />
      </div>

      {preview && (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={preview}
          alt="Item preview"
          className="h-56 w-56 rounded-xl border border-stone-200 object-cover"
        />
      )}

      {file && step === "pick" && (
        <button
          onClick={analyze}
          className="rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white"
        >
          Analyze with AI
        </button>
      )}

      {step === "analyzing" && (
        <p className="text-sm text-stone-500">
          Extracting attributes. This takes a few seconds.
        </p>
      )}

      {error && <p className="text-sm text-red-600">{error}</p>}

      {(step === "review" || step === "saving") && (
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-4 rounded-xl border border-amber-200 bg-amber-50 p-5"
        >
          <p className="text-sm text-amber-900">
            These details were generated by AI and can be wrong. Check and
            correct them before saving.{" "}
            {attrs.confidence_notes && `AI notes: ${attrs.confidence_notes}`}
          </p>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <label className="block text-sm">
              Category
              <select
                value={attrs.category}
                onChange={(e) =>
                  setField(
                    "category",
                    e.target.value as ClothingAttributes["category"],
                  )
                }
                className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
              >
                {CLOTHING_CATEGORIES.map((c) => (
                  <option key={c} value={c}>
                    {c}
                  </option>
                ))}
              </select>
            </label>

            <label className="block text-sm">
              Subcategory
              <input
                value={attrs.subcategory}
                onChange={(e) => setField("subcategory", e.target.value)}
                placeholder="e.g. t-shirt, chinos, sundress"
                className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
              />
            </label>

            <label className="block text-sm">
              Primary colour
              <input
                value={attrs.primary_colour}
                onChange={(e) => setField("primary_colour", e.target.value)}
                className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
              />
            </label>

            <label className="block text-sm">
              Secondary colours (comma separated)
              <input
                value={attrs.secondary_colours.join(", ")}
                onChange={(e) =>
                  setField(
                    "secondary_colours",
                    e.target.value
                      .split(",")
                      .map((s) => s.trim())
                      .filter(Boolean),
                  )
                }
                className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
              />
            </label>

            <label className="block text-sm">
              Pattern
              <input
                value={attrs.pattern}
                onChange={(e) => setField("pattern", e.target.value)}
                className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
              />
            </label>

            <label className="block text-sm">
              Material cues
              <input
                value={attrs.material_cues}
                onChange={(e) => setField("material_cues", e.target.value)}
                className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
              />
            </label>

            <label className="block text-sm">
              Formality
              <select
                value={attrs.formality}
                onChange={(e) =>
                  setField(
                    "formality",
                    e.target.value as ClothingAttributes["formality"],
                  )
                }
                className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
              >
                {FORMALITY_LEVELS.map((f) => (
                  <option key={f} value={f}>
                    {f}
                  </option>
                ))}
              </select>
            </label>

            <label className="block text-sm">
              Layering role
              <select
                value={attrs.layering_role}
                onChange={(e) =>
                  setField(
                    "layering_role",
                    e.target.value as ClothingAttributes["layering_role"],
                  )
                }
                className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
              >
                {LAYERING_ROLES.map((r) => (
                  <option key={r} value={r}>
                    {r}
                  </option>
                ))}
              </select>
            </label>
          </div>

          <fieldset className="text-sm">
            <legend className="font-medium">Suitable weather</legend>
            <div className="mt-2 flex flex-wrap gap-3">
              {WEATHER_TAGS.map((tag) => (
                <label key={tag} className="flex items-center gap-1.5">
                  <input
                    type="checkbox"
                    checked={attrs.weather_tags.includes(tag)}
                    onChange={(e) =>
                      setField(
                        "weather_tags",
                        e.target.checked
                          ? [...attrs.weather_tags, tag]
                          : attrs.weather_tags.filter((t) => t !== tag),
                      )
                    }
                  />
                  {tag}
                </label>
              ))}
            </div>
          </fieldset>

          <label className="block text-sm">
            Your notes (optional)
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={2}
              className="mt-1 w-full rounded-lg border border-stone-300 px-3 py-2"
            />
          </label>

          <button
            onClick={save}
            disabled={step === "saving"}
            className="rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
          >
            {step === "saving" ? "Saving..." : "Confirm and save to wardrobe"}
          </button>
        </motion.div>
      )}
    </div>
  );
}
